name: Report Standard violations
on:
  push:
    branches: [main]
    paths:
      - "**.js"
  pull_request:
    branches: [main]
    paths:
      - "**.js"
  workflow_dispatch:
jobs:
  standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15.3.0"
      - run: npm i -D
      - run: npm run s
